// Generated by LiveScript 1.4.0
(function(){
  var safe, objMerge, maybe, out$ = typeof exports != 'undefined' && exports || this;
  out$.safe = safe = function(f, params, err){
    var e;
    try {
      return f(params);
    } catch (e$) {
      e = e$;
      console.log(e);
      if (err) {
        return err(e);
      }
    }
  };
  out$.objMerge = objMerge = function(x, y){
    var lstX, lstY;
    lstX = objToPairs(x);
    lstY = objToPairs(y);
    return pairsToObj(
    union(lstX(lstY)));
  };
  out$.maybe = maybe = function(v){
    var nothing, something, this$ = this;
    nothing = {
      bind: function(fn){
        return this;
      },
      isNothing: function(){
        return true;
      },
      val: function(){
        return Error("cannot call val on nothing");
      },
      maybe: function(def, fn){
        return def;
      }
    };
    return something = {
      bind: function(fn){
        return maybe(fn(this$, value));
      },
      isNothing: function(){
        return false;
      },
      val: function(){
        return v;
      },
      maybe: function(def, fn){
        return fn(this$, value);
      }
    };
  };
}).call(this);
