// Generated by LiveScript 1.4.0
(function(){
  var orm, sha256, sec, ran, v, pat, User, Video, Answer, out$ = typeof exports != 'undefined' && exports || this;
  orm = require("orm");
  sha256 = require("crypto-js/sha256");
  sec = orm.enforce.security;
  ran = orm.enfoce.ranges;
  v = orm.enforce;
  pat = orm.patterns;
  out$.User = User = db.define("user", {
    username: String,
    email: String,
    password: String,
    password2: String,
    validations: {
      username: [
        v.notEmptyString('Required'), v.required('Required (this may be a system error)'), sec.username({
          length: 3
        }, 'Must be greater than 3 characters long')
      ],
      password: [sec.password('luns6', 'Must have 6 characters, upper/lower case and a special character'), v.notEmptyString('Required'), v.required('Required (this may be a system error)')],
      password2: v.sameAs('password', 'Must match password'),
      email: pat.email('Must be a valid email')
    },
    hooks: {
      beforeSave: function(next){
        this.password = SHA256(this.password);
        this.password2 = void 8;
        return next;
      }
    }
  });
  out$.Video = Video = db.define("video", {
    url: String,
    validations: {
      url: void 8
    },
    hooks: beforeSave(function(next){
      return this.url.match(/(?:(?:youtube.*v=)([^"]+)(?:&)|(?:youtu\.be\/)(.+))(?:\n*)/);
    })
  });
  out$.Answer = Answer = db.define("answer", {
    total: Int,
    correct: Int
  });
}).call(this);
